[10.0] [MIG] l10n be partner identification lmi
OCA/l10n-belgium pull request #41
Opened 2017-01-17 15:31 UTC by lmignon

2017-01-17 15:35 UTC, rousseldenis approved these changes
Code Review

2017-01-20 11:19 UTC, rousseldenis requested changes

2017-01-20 11:19 UTC, rousseldenis commented on l10n_be_partner_identification/tests/test_l10n_be_partner_identification.py
> +import openerp.tests.common as common
Oups! Didn't pay attention to this...

2017-02-05 16:44 UTC, sbidoul commented
@lmignon @rousseldenis regarding this PR and #42, should we have one module per identification number (in which case, the module name in this PR must suffixed with `rrn` or something). Or create one module for all be identification schemes? In which case #42 must be merged into this one.

2017-02-05 16:58 UTC, rousseldenis commented
IMO, it's quite difficult to identify every belgian scheme (unknown ones). So, by case, we create specialized module based on partner-contact repo one. Suffixing this one with rrn should be the solution.

2023-10-15 12:24 UTC, closed without merging